---
title: "Fading Stars Replication"
author: "Jonah Wolf"
format: pdf
editor: visual
---

## Introduction

This paper is a replication of Gutiérrez and Philippon (2019), itself a response to Autor et al. (2020). Gutiérrez and Philippon dispute the argument from Autor et al. that growth of the U.S. profit share might be explained by the increasing prevalence of highly productive firms. As part of their analysis, they use firm-year observations in the Compustat database identify the share of sales accruing to the top twenty firms by market value and the top four firms by market value in each BEA industry, arguing that "contrary to common wisdom, the stars have not become larger in terms of sales" (313).

## Replication Procedure

Since I had access to the authors' replication package, but no experience with Stata, I set myself the task of adapting the replication package to R. I did this with help from the Claude AI chatbot, though frequently came up with simpler R commands once I understood the purpose of each Stata command. I maintained the structure of the authors' code, and for most scripts kept their Stata code as commented text above the corresponding R code. Since I focused on replicating figure 1b from the paper, I didn't include data on employment, foreign sales, or productivity.

I ran the entire Stata replication package, which generated multiple ".dta" data files that I could use as benchmarks for each step of the analysis. I also wrote a script using the base R "all.equal" function to compare each of these ".dta" datasets to the datasets generated by my R scripts. For each R script, I started with the replication data so that any possible discrepancies could only be attributed to a single R script.

## Data Sources

Gutiérrez and Philippon use a script titled "cs_download" to download a table of public company identifiers ("gvkey") and SIC and NAICS industry codings from Compustat's "comp_na_daily_all.company" table, and data on market fundamentals from the "Merged Fundamental Annual File" ("funda"). They filter this data to include data from consolidated balance sheets, from industrial (non-financial) companies, from standardized balance sheets, from domestic firms, and with data in US dollars. The authors download data on prices and shares outstanding from the Center for Research on Security Prices (CRSP) "crspmsf" table and linking identifiers from the CRSP/Compustat Merged ("CCM") linktable.

## Consolidation

The authors use a script called "cs_load" to consolidate the Compustat and CRSP data into a dataset called "NA_compustat." They restrict the combined dataset to observations from 2017 or earlier, and a calculation of profit shares as the ratio of operating income after depreciation to sales, winsorized at 96%. They generate two- and three-digit SIC codes, and two-through-six-digit NAICS codes. They then update the four-digit NAICS codes using concordances from the Census bureau. Observations with missing NAICS codes are mapped to the most common NAICS code for the given SIC code. They then merge in BEA codes from a "NAICS2BEA" mapping file.

I used the R "all.equal" function to compare the "NA_compustat" dataset generated from my R code to the one generated from the authors' Stata code. The mean relative difference for each variable in the two datasets was below 0.05, with the exceptions of "prcc_f" ("Price Close - Annual - Fiscal") and "fyr" ("Fiscal Year-end Month"), neither of which seems to be used in the analysis. I also added checkpoints after the creation of each variable in the script to check the mean and median against those produced by the data script, and couldn't identify any discrepancies.

## Other Data Sources

I also followed the authors in generating tables of national and industry-level data on output (and chained quantity index) and employment from FRED (national) and BEA (industry-level). The results from my scripts seem to match those from the authors'.

## Data Work

The authors use a script called "main_datawork" to prepare a dataset called "main_dataset_firm." They restrict the sample to observations from 1955 to 2017. They merge in BEA industry codes and industry-level BEA data on output and employment. (For this replication I skipped the employment data.)

As with the raw data, the only variables that seem to have significant differences are "prcc_f" and "fyr."

## Analysis

The final analysis is done in a script called "aWork_stars." The authors filter the dataset to firm-years located in the US with positive sales, employment, and total assets ("at"). They calculate the share of each firm's sales in total output ("sy"), and identify "stars" (the top twenty firms by market value in each year) and "industry stars" (top four firms by market value in each BEA industry in each year).

The final dataset ("tempanalysis_stars") produced by my script contains more observations than that produced by the replication script. This can probably be explained by the fact that the authors filter by two variables that I didn't calculate (labor productivity and three-year growth rate).
